daemonize yes
pidfile "/home/zz/redis/7010/sentinel.pid"
port 7010
bind 192.168.100.1
loglevel notice
logfile "/home/zz/redis/7010/log/sentinel.log"

#protected-mode yes
dir "/home/zz/redis/7010/data"

# Generated by CONFIG REWRITE
sentinel monitor mymaster 192.168.100.1 7000 1
sentinel auth-pass mymaster zz123!
sentinel down-after-milliseconds mymaster 3000
